services:
  - type: web
    name: leukemia-backend
    env: python
    repo: https://github.com/KapadiaOm/Leukemia-Classifier
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free

  - type: static_site
    name: leukemia-frontend
    repo: https://github.com/KapadiaOm/Leukemia-Classifier
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    plan: free
