services:
  - type: web
    name: leukemia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      workingDir: backend
    start:
      workingDir: backend

  - type: static_site
    name: leukemia-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    build:
      workingDir: frontend
